name: Notify to weixin
on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    # 早上8点
    - cron: '40 23 * * *'
# on:
#   push:
#     branches:
#       - master

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node@14.x # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: 14

        # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # prepare 钩子会在安装完成后自动 build
      # - name: Build
      #   run: npm run build

      # 运行脚本
      - name: 运行脚本
        run: npm run notify
        env:
          WX_COMPANY_ID: ${{ secrets.WX_COMPANY_ID }}
          WX_APP_ID: ${{ secrets.WX_APP_ID }}
          WX_APP_SECRET: ${{ secrets.WX_APP_SECRET }}
          WX_BOT_KEY: ${{ secrets.WX_BOT_KEY }}
